<?php
/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class CountDownTimer {
	private $count_down_timer_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'count_down_timer_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'count_down_timer_page_init' ) );
	}

	public function count_down_timer_add_plugin_page() {
		add_menu_page(
			'Count Down Timer', // page_title
			'Count Down Timer', // menu_title
			'manage_options', // capability
			'count-down-timer', // menu_slug
			array( $this, 'count_down_timer_create_admin_page' ), // function
			'dashicons-backup', // icon_url
			81 // position
		);
	}

	public function count_down_timer_create_admin_page() {
		$this->count_down_timer_options = get_option( 'count_down_timer_option_name' ); ?>

		<div class="wrap">
			<h2>Count Down Timer</h2>
			<p></p>
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'count_down_timer_option_group' );
					do_settings_sections( 'count-down-timer-admin' );
					submit_button();
				?>
			</form>
		</div>
	<?php }

	public function count_down_timer_page_init() {
		register_setting(
			'count_down_timer_option_group', // option_group
			'count_down_timer_option_name', // option_name
			array( $this, 'count_down_timer_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'count_down_timer_setting_section', // id
			'Settings', // title
			array( $this, 'count_down_timer_section_info' ), // callback
			'count-down-timer-admin' // page
		);

		add_settings_field(
			'compact_0', // id
			'compact', // title
			array( $this, 'compact_0_callback' ), // callback
			'count-down-timer-admin', // page
			'count_down_timer_setting_section' // section
		);

		add_settings_field(
			'layout_1', // id
			'layout', // title
			array( $this, 'layout_1_callback' ), // callback
			'count-down-timer-admin', // page
			'count_down_timer_setting_section' // section
		);

		add_settings_field(
			'language_2', // id
			'language', // title
			array( $this, 'language_2_callback' ), // callback
			'count-down-timer-admin', // page
			'count_down_timer_setting_section' // section
		);

		add_settings_field(
			'messge_3', // id
			'messge', // title
			array( $this, 'messge_3_callback' ), // callback
			'count-down-timer-admin', // page
			'count_down_timer_setting_section' // section
		);
	}

	public function count_down_timer_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['compact_0'] ) ) {
			$sanitary_values['compact_0'] = $input['compact_0'];
		}

		if ( isset( $input['layout_1'] ) ) {
			$sanitary_values['layout_1'] = sanitize_text_field( $input['layout_1'] );
		}

		if ( isset( $input['language_2'] ) ) {
			$sanitary_values['language_2'] = $input['language_2'];
		}

		if ( isset( $input['messge_3'] ) ) {
			$sanitary_values['messge_3'] = esc_textarea( $input['messge_3'] );
		}

		return $sanitary_values;
	}

	public function count_down_timer_section_info() {
		
	}

	public function compact_0_callback() {
		printf(
			'<input type="checkbox" name="count_down_timer_option_name[compact_0]" id="compact_0" value="compact_0" %s> <label for="compact_0">Enable</label>',
			( isset( $this->count_down_timer_options['compact_0'] ) && $this->count_down_timer_options['compact_0'] === 'compact_0' ) ? 'checked' : ''
		);
	}

	public function layout_1_callback() {
		printf(
			'<input class="regular-text" type="text" name="count_down_timer_option_name[layout_1]" id="layout_1" value="%s">',
			isset( $this->count_down_timer_options['layout_1'] ) ? esc_attr( $this->count_down_timer_options['layout_1']) : ''
		);
	}

	public function language_2_callback() {
		?> <select name="count_down_timer_option_name[language_2]" id="language_2">
			<?php $selected = (isset( $this->count_down_timer_options['language_2'] ) && $this->count_down_timer_options['language_2'] === 'es') ? 'selected' : '' ; ?>
			<option value="es" <?php echo $selected; ?>>Spanish</option>
			<?php $selected = (isset( $this->count_down_timer_options['language_2'] ) && $this->count_down_timer_options['language_2'] === 'de') ? 'selected' : '' ; ?>
			<option value="de" <?php echo $selected; ?>>Deutchs</option>
			<?php $selected = (isset( $this->count_down_timer_options['language_2'] ) && $this->count_down_timer_options['language_2'] === 'fr') ? 'selected' : '' ; ?>
			<option value="fr" <?php echo $selected; ?>>French</option>
			<?php $selected = (isset( $this->count_down_timer_options['language_2'] ) && $this->count_down_timer_options['language_2'] === 'it') ? 'selected' : '' ; ?>
			<option value="it" <?php echo $selected; ?>>Italian</option>
		</select> <?php
	}

	public function messge_3_callback() {
		printf(
			'<textarea class="large-text" rows="5" name="count_down_timer_option_name[messge_3]" id="messge_3">%s</textarea>',
			isset( $this->count_down_timer_options['messge_3'] ) ? esc_attr( $this->count_down_timer_options['messge_3']) : ''
		);
	}

}
if ( is_admin() )
	$count_down_timer = new CountDownTimer();

/* 
 * Retrieve this value with:
 * $count_down_timer_options = get_option( 'count_down_timer_option_name' ); // Array of All Options
 * $compact_0 = $count_down_timer_options['compact_0']; // compact
 * $layout_1 = $count_down_timer_options['layout_1']; // layout
 * $language_2 = $count_down_timer_options['language_2']; // language
 * $messge_3 = $count_down_timer_options['messge_3']; // messge
 */
